# Generated by Django 2.2.7 on 2019-12-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel_Census',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField()),
                ('Longtitude', models.FloatField()),
                ('Unique_Squirrel_ID', models.CharField(max_length=100)),
                ('Shift', models.CharField(max_length=2)),
                ('Date', models.DateField()),
                ('Age', models.CharField(max_length=15)),
                ('Primary_Fur_Color', models.CharField(max_length=15)),
                ('Location', models.CharField(max_length=100)),
                ('Specific_Location', models.CharField(max_length=100)),
                ('Running', models.BooleanField()),
                ('Chasing', models.BooleanField()),
                ('Climbing', models.BooleanField()),
                ('Eating', models.BooleanField()),
                ('Foraging', models.BooleanField()),
                ('Other_Activities', models.CharField(max_length=100)),
                ('Kuks', models.BooleanField()),
                ('Quaas', models.BooleanField()),
                ('Moans', models.BooleanField()),
                ('Tail_flags', models.BooleanField()),
                ('Tail_twitches', models.BooleanField()),
                ('Approaches', models.BooleanField()),
                ('Indifferent', models.BooleanField()),
                ('Runs_from', models.BooleanField()),
            ],
        ),
    ]
