# Generated by Django 2.2.7 on 2019-12-02 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SquirrelTracker', '0002_auto_20191202_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel_census',
            old_name='primary_Fur_Color',
            new_name='primary_fur_color',
        ),
    ]
