# Generated by Django 2.2.7 on 2019-12-03 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SquirrelTracker', '0003_auto_20191202_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel_census',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
