from django.db import models

class Squirrel_Census(models.Model):
    latitude = models.FloatField()
    longitude = models.FloatField()
    unique_squirrel_id = models.CharField(max_length=100)
    shift = models.CharField(max_length=2)
    date = models.DateField(auto_now=False,auto_now_add=False)
    age = models.CharField(max_length=15)
    primary_fur_color = models.CharField(max_length=15)
    location = models.CharField(max_length=100)
    specific_location = models.CharField(max_length=100)
    running = models.BooleanField()
    chasing = models.BooleanField()
    climbing = models.BooleanField()
    eating = models.BooleanField()
    foraging = models.BooleanField()
    other_activities = models.CharField(max_length=100)
    kuks = models.BooleanField()
    quaas = models.BooleanField()
    moans = models.BooleanField()
    tail_flags = models.BooleanField()
    tail_twitches = models.BooleanField()
    approaches = models.BooleanField()
    indifferent = models.BooleanField()
    runs_from = models.BooleanField()
